# Generated by Django 2.2 on 2019-12-08 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('users', '0002_remove_customuser_custom_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reader',
        ),
    ]
