# Generated by Django 2.2 on 2019-12-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20191208_1311'),
        ('users', '0003_delete_reader'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='books',
            field=models.ManyToManyField(related_name='books', to='books.Book'),
        ),
    ]
